name: Deploy via SCP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Prepare SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts

      - name: delete SCP目標資料內容
        run: |
          rm -rf ~/php-app/*

      - name: Upload by SCP
        run: |
          scp -i ~/.ssh/id_rsa -r  composer.json composer.lock src Dockerfile docker-compose.yml index.php upload ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:~/php-app/

      - name: Restart service
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} '
            cd ~/php-app &&
            docker build -t my-php-app . &&
            docker stop php-container || true &&
            docker rm php-container || true &&
            docker run -d --name php-container -p 80:80 my-php-app
          '
